spring:
  thymeleaf:
    suffix: .html
    prefix: classpath:templates/thymeleaf/
    cache: false # ?????? ??
    check-template-location: true
    mode: HTML
  mvc:
    static-path-pattern: "/static/**"

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: profile,email

  datasource:
    url: jdbc:mysql://ec2-3-37-254-120.ap-northeast-2.compute.amazonaws.com:3306/develog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect